NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import BecomeAnAuthor, profile, ChangePasswordView # , ShowProfilePageView, CreateProfilePageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    path('success/', BecomeAnAuthor.as_view(), name = 'success'),
    path('profile/', profile, name='users-profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewsPaper/news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, SearchList, PostsAdd, PostEdit, PostDelete, SubscribeToCategory, UnSubscribeToCategory
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', cache_page(60*5) (PostsList.as_view())), 
    # path('<int:pk>', cache_page(60*5) (PostDetail.as_view()), name='details'),
    path('<int:pk>', PostDetail.as_view(), name='details'),
    path('search', SearchList.as_view(), name='search'),
    path('add', PostsAdd.as_view()), 
    path('<int:pk>/edit/', PostEdit.as_view(), name='edit_post'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='delete_post'),
    path('<int:pk>/subscribe/', SubscribeToCategory.as_view(), name = 'subscribe'),
    path('<int:pk>/unsubscribe/', UnSubscribeToCategory.as_view(), name = 'unsubscribe'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.core.cache import cache

class Author(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    user_rating = models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.username}'
    
    def update_rating(self):
        author_rating = Post.objects.filter(author__exact=self).values('rating')
        author_comments = Comment.objects.filter(user__exact=User.objects.get(id__exact=self.id)).values('comment_rating')
        sum_of_author_comments = 0
        for i in author_comments:
            sum_of_author_comments += i['comment_rating']
        comments_to_author_articles = Comment.objects.filter(post__exact=Post.objects.filter(author__exact=self)[:1]).values('comment_rating')
        sum_of_comments_to_author_articles = 0
        for i in comments_to_author_articles:
            sum_of_comments_to_author_articles += i['comment_rating']
        self.user_rating = 3*author_rating[0]['rating']+sum_of_author_comments+sum_of_comments_to_author_articles
        self.save()


class Category(models.Model):
    name = models.CharField(unique=True, max_length=255, null=False)
    user = models.ManyToManyField(User, through = 'UsersSubscribed')

    def __str__(self):
        return f'{self.name}'

    # def user(self):
    #     # return f'{self.userssubscribed_set.all()}'
    #     users = []
    #     for each in self.userssubscribed_set.all().values():
    #         users.append(User.objects.get(id=each['user_id']).username)
    #     return ', '.join(users)

    # @property
    # def userssubscribed(self):
    #     return f'{self.userssubscribed_set.all().count()}' 

class UsersSubscribed(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.user} is subscribed to category {self.category}'
    
class Post(models.Model):
    author = models.ForeignKey(Author, null=False, on_delete = models.CASCADE)
    article = 'ar'
    news = 'nw'
    TYPES = [
        (article, 'Статья'),
        (news, 'Новость'),
    ]
    type = models.CharField(max_length = 2, 
                                choices = TYPES, 
                                default = news)
    creation_date_time = models.DateTimeField(auto_now_add = True)
    category = models.ManyToManyField(Category, through = 'PostCategory')
    header = models.CharField(max_length=255, null=False)
    main_text = models.TextField()
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()


    def dislike(self):
        if self.rating:
            self.rating -= 1
        self.save()


    def preview(self):
        return self.main_text[:124]+'...'

    # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с новостью
    def get_absolute_url(self): 
        return f'/news/{self.id}'  # FIXME Стоит заменить на переменную
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_text = models.TextField()
    creation_date_time = models.DateTimeField()
    comment_rating = models.IntegerField(default=0)


    def like(self):
        self.comment_rating += 1
        self.save()


    def dislike(self):
        if self.comment_rating:
            self.comment_rating -= 1
        self.save()

# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_userpic.png', upload_to='images/profile/')
    bio = models.TextField()

    def __str__(self):
        return self.user.username
    
    # resizing images
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

NewsPaper/templates/author_success.html
{% extends 'flatpages/default.html' %} 
 
{% block title %}
Вы стали автором
{% endblock title %}
 
{% block content %}
    <h1>Поздравляем, {{ user.get_username }}!</h1>
        <h2>Вы стали автором!</h2>
{% endblock content %}

NewsPaper/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

NewsPaper/templates/change_password.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

NewsPaper/templates/mail_to_subscribers.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ header }}</title>
</head>
<body>
    <h2>{{ hello_text }}</h2>
    <p>{{ main_text|truncatechars:50 }}</p>
</body>
</html>

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Подробности
{% endblock title %}
 
{% block content %}
    <h1>{{ post.header | censor }}</h1>
    {% for each in post.category.filter %}
    [ {{each}} ]
    {% endfor %}
    <i>{{ post.creation_date_time| date:'d-M-Y g:i' }} |
    {{ post.author.username.first_name}} {{ post.author.username.last_name}}</i>
    <a href="{% url 'edit_post' post.id %}">[Редактировать]</a>
    <a href="{% url 'delete_post' post.id %}">[Удалить]</a>
    <hr>
    {{ post.main_text | censor }}
    <p>
    {% for each in post.category.filter %}
    <a href="{% url 'subscribe' each.id %}">[ Подписаться на категорию {{ each }} ]</a>
    {% endfor %}
    </p>
{% endblock content %}

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Удаление публикации
{% endblock title %}
 
{% block content %}
<h1>Удаление публикации</h1>
<h2>Вы действительно хотите удалить эту публикацию?</h2>

<b>{{ post.header | censor }}</b><br>
<i>{{ post.creation_date_time| date:'d-M-Y g:i' }} |
{{ post.author.username.first_name}} {{ post.author.username.last_name}}</i><br>
{{ post.main_text|censor|truncatechars:200 }}

    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Удалить публикацию"> 
    </form>    
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Изменить публикацию
{% endblock title %}
 
{% block content %}
{% if is_not_author %}
<h1>Ошибка! Нет прав на изменение публикации.</h1>
<a class="btn-common-blue" href="{% url 'success' %}">Стать автором</a>
{% else %}
<form method="POST">
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Изменить публикацию">
</form>
{% endif %}

{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Новости
{% endblock title %}
 
{% block content %}
<h1>Все новости</h1>
    <h3>{{ time_now }}</h3> 
    Новостей: {{ posts | length}} шт.
    <hr>
    {% if posts %} 
        {% for post in posts %}
            <span><h3><a href="{{ post.id }}">{{ post.header | censor  }} </a></h3>
            <p>
                {% for each in post.category.filter %}
                [ {{each}} ]
                {% endfor %}
                 <i>{{ post.creation_date_time| date:'d-M-Y g:i' }} |
                  {{ post.author.username.first_name}} {{ post.author.username.last_name}}</i><br>
            {{ post.main_text|censor|truncatechars:50 }}
            <br>
            <a href="{% url 'edit_post' post.id %}">[Редактировать]</a>
            <a href="{% url 'delete_post' post.id %}">[Удалить]</a>
            </p>
            </span>
        {% endfor %}
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
    {% if is_paginated %}  <!-- Pagination block -->
        <!-- Previous page and first page -->
        {% if page_obj.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}
    
        <!-- Current page and neigbours -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
    
        <!-- Next page and last page link -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">>>></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

NewsPaper/templates/posts_add.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Добавление публикации
{% endblock title %}
 
{% block content %}
{% if is_not_author %}
<h1>Ошибка! Нет прав на добавление публикации.</h1>
<a class="btn-common-blue" href="{% url 'success' %}">Стать автором</a>
{% else %}
<h1>Добавление публикации</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <label for="authors">Автор</label>

        <select name="authors"> 
            {% for author in authors %} 
                <option value="{{ author.id }}"> {{ author.username }} [{{ author.username.first_name}} {{ author.username.last_name}}]</option> 
            {% endfor %} 
        </select> 

        <label for="type">Тип публикации</label>
        <select name="type"> 
            {% for key, value in types %} 
                <option value="{{ key }}">{{ value }}</option> 
            {% endfor %} 
        </select>         
        <br>
        <label for="header">header</label>
        <input name="header">

        <br>
        <label for="main_text">main_text</label>
        <textarea name="main_text">Write something here</textarea>
        
        <label for="rating">rating</label>
        <input name="rating" min="0" type="number" value="0">
    
    <!-- Здесь будет список категорий. --> 
    <select name="category"> 
        {% for category in categories %} 
            <option value="{{ category.id }}"> {{ category.name }} </option> 
        {% endfor %} 
    </select> 
    <input type="submit" value="Добавить публикацию"> </form>
{% endif %}
{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
 
{% block title %}
Новости
{% endblock title %}
 
{% block content %}
<h1>Все новости</h1>
    <h3>{{ time_now }}</h3> 
    Новостей: {{ posts | length}} шт.
    <hr>
    <form method="GET">
        {{ filter.form }} <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самому -->
        <input type="submit" value="Найти">
    </form>
    <hr>
    {% if posts %} 
        {% for post in filter.qs %}
            <span><h3><a href="{{ post.id }}">{{ post.header | censor  }} </a></h3>
            <p><i>{{ post.creation_date_time| date:'d-M-Y g:i' }}</i> |
            <i>{{ post.author.username}} [{{ post.author.username.first_name}} {{ post.author.username.last_name}}]</i><br>
            {{ post.main_text|censor|truncatechars:50 }}</p></span>
        {% endfor %}
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %} 
 
{% block title %}
Успешная подписка
{% endblock title %}
 
{% block content %}
    <h1>Поздравляем, {{ user.get_username }}!</h1>
        <h2>Вы успешно подписались на категорию {{ subscribed.name }}!</h2>
{% endblock content %}

NewsPaper/templates/too_many_publications.html
{% extends 'flatpages/default.html' %} 
 
{% block title %}
Слишком много публикаций
{% endblock title %}
 
{% block content %}
    <h1>{{ user.get_username }}, вы опубликовали много материала сегодня!</h1>
        <h2>Позвольте пользователям прочитать его. И добавьте свежий материал завтра.</h2>
{% endblock content %}

NewsPaper/templates/unsubscribe.html
{% extends 'flatpages/default.html' %} 
 
{% block title %}
Успешная отписка
{% endblock title %}
 
{% block content %}
    <h1>Поздравляем, {{ user.get_username }}!</h1>
        <h2>Вы успешно отписались от категории {{ unsubscribed.name }}!</h2>
{% endblock content %}

NewsPaper/templates/user_profile.html
{% extends 'flatpages/default.html' %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <div class="my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if user.category_set.filter %}
    <div class="col-md-5"><p>
        Подписан на разделы:<br>
        {% for each in user.category_set.filter %}
        [ {{ each }}  <a href="{% url 'unsubscribe' each.id %}">Отписаться</a>]<br>
        {% endfor %}
    </p></div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                            {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                            {{ user_form.email }}
                    </div>
                    <div class="form-group">
                        <a href="{% url 'password_change' %}">Change Password</a>
                        <hr>
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
            <button type="reset" class="btn btn-dark btn-lg">Reset</button>
        </form>
    </div>
{% endblock content %}